ALPP/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import feedback.views
import registration_handle.views
from ALPP import settings
from ALPP.swagger import schema_view

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('',  include('registration_handle.urls')),
    path("accounts/", include("allauth.urls")),
    path('profile/', include("profile_page.urls")),
    path('register/', registration_handle.views.register, name='register'),
    path('langs/', include("modules.urls")),
    path('about/', registration_handle.views.about, name='about'),
    path('forums/', include("discussion_forums.urls")),
    path('resources/', include("resource_library.urls")),
    path('feedback/', feedback.views.feedback, name='feedback'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

modules/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


class Language(models.Model):
    name = models.CharField(max_length=100)
    joke = models.TextField()

    def __str__(self):
        return self.name


class Lesson(models.Model):
    title = models.CharField(max_length=100)
    module = models.ForeignKey('Module', on_delete=models.CASCADE, default="1")
    description = models.TextField()
    difficulty_level = models.CharField(
        max_length=20,
        choices=[
            ('easy', _('Easy')),
            ('medium', _('Medium')),
            ('hard', _('Hard')),
        ],
        default='easy'
    )
    order = models.IntegerField(default=1)
    sections = models.ManyToManyField('Section', related_name='lessons')

    def __str__(self):
        return self.title


class Quiz(models.Model):
    title = models.CharField(max_length=100)
    module = models.ForeignKey('Module', on_delete=models.CASCADE, default="1")
    description = models.TextField()
    difficulty_level = models.CharField(
        max_length=20,
        choices=[
            ('Easy', 'Easy'),
            ('Medium', 'Medium'),
            ('Hard', 'Hard'),
        ],
        default='Easy'
    )
    order = models.IntegerField(default=1)
    questions = models.ManyToManyField('Question', related_name='quizzes')

    def __str__(self):
        return self.title


class Module(models.Model):
    title = models.CharField(max_length=100)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.title


class Section(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    contents = models.TextField()

    def __str__(self):
        return self.title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    question_type = models.CharField(max_length=50, choices=[('Single Choice', 'Single Choice'),
                                                             ('Multiple Choice', 'Multiple Choice'),
                                                             ('Open Text', 'Open Text')])

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    is_correct = models.CharField(max_length=15, choices=[("Correct", "Correct"), ("Incorrect", "Incorrect")],
                                  default="Incorrect")

    def __str__(self):
        return self.text

templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sniglet:wght@400;800&display=swap" rel="stylesheet">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <title>About</title>
</head>
<body>
<article class="sidebar">
    <a class="sniglet" href="{% url "profile_page" username=request.user.username %}"><img src="{% static "/leeri_logo.png" %}" style="height: 210px; width: 210px; margin-left: -10px; margin-bottom: -50px" alt="leari on a plane"></a>
    <p class="sniglet" style="color: white; font-size: 25px">Airplane Learning</p>
    <hr style="color: white; width: 100%">
    <a class="sniglet">Logged in as: {{ request.user.username }}</a>
    <hr style="color: white; width: 100%">
    <a class="sniglet" href="{% url "profile_page" username=request.user.username %}">Profile</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url "modules_list" language_id=user.profile.chosen_language.id %}">Modules</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="/forums">Discussion Forums</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="/feedback">Feedback Form</a>
    <br>
    <br>
    <a href="{% url 'profile_settings' %}" class="sniglet" style="font-size: 15px; ">Settings</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url 'schema-swagger-ui' %}">Swagger</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url 'logout' %}">Log out</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px"><u>About</u></a>
    <footer class="sniglet" style="bottom: 45px; left: 75px">
        <p>© gearbeagel</p>
    </footer>
</article>
<div style="margin: -350px 0 0 -200px; width: 500px">
    <img src="{% static "leeri_stare.png" %}" style="height: 30%; width: 30%; margin-bottom: -25px; margin-left: 25px; margin-right: 25px;" alt="{{ user.username }}'s profile picture">
    <h2 class="sniglet" style="color: #d39c3f; margin-bottom: -15px; text-align: center">Victoria Kondatska</h2>
    <hr style="border: none; border-top: 3px solid #d39c3f; width: 100%; margin-top: 20px;">
    <p class="sniglet" style="color: #637d91; margin-bottom: -5px">Airplane Learning: Polyglot Pro (Project №13)</p>
    <hr style="border: none; border-top: 3px solid #d39c3f; width: 100%; margin-top: 20px;">
    <!-- Telegram icon -->
    <h3 class="sniglet" style="margin-bottom: -5px"><a href="https://t.me/gearbeagel" style="color: #637d91"><i class="fab fa-telegram"></i> Telegram</a></h3>
    <hr style="border: none; border-top: 3px solid #d39c3f; width: 100%; margin-top: 20px;">
    <!-- Email icon -->
    <h3 class="sniglet" style="color: #637d91; margin-bottom: -5px"><a style="color: #637d91" href="mailto:kondratskayavictoria@gmail.com"><i class="fas fa-envelope"></i> Email</a></h3>
    <hr style="border: none; border-top: 3px solid #d39c3f; width: 100%; margin-top: 20px;">
    <!-- GitHub icon -->
    <h3 class="sniglet" style="color: #637d91; margin-bottom: -5px"> <a style="color: #637d91" href="https://github.com/gearbeagel/Kondratska.University.AirplaneLearning"><i class="fab fa-github"></i> Github</a></h3>
</div>
</body>
</html>

templates/base.html
{% load socialaccount %}
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sniglet:wght@400;800&display=swap" rel="stylesheet">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <title>{% block title %}Profile{% endblock %}</title>
    <style>
        body {
            font-family: 'Sniglet', cursive;
            display: flex;
        }
        .sidebar {
            width: 250px;
            background-color: #d39c3f;
            color: white;
            padding: 15px;
            height: 100vh;
            position: fixed;
            top: 0;
            left: 0;
            text-align: center;
        }
        .sidebar a {
            color: white;
            text-decoration: none;
            display: block;
            padding: 10px 0;
        }
        .sidebar img {
            height: 210px;
            width: 210px;
            display: block;
            margin: 0 auto 20px;
        }
        .sidebar p {
            text-align: center;
            font-size: 20px;
        }
        .sidebar hr {
            border-top: 1px solid white;
            margin: 15px 0;
        }
        .content {
            margin-left: 300px;
            padding: 20px;
            width: calc(100% - 300px);
        }
        span.active-link {
            text-decoration: underline;
            color: white;
        }
        @media (max-width: 768px) {
            .sidebar {
                width: 100%;
                height: auto;
                position: relative;
            }
            .content {
                margin-left: 0;
                width: 100%;
            }
        }
        h3 {
            font-family: Sniglet, system-ui;
        }
        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: #ffffff; /* Background color to match your page background */
            z-index: 9999;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        /* You may need to adjust the size and position of the video */
        .loader {
            width: 600px; /* Adjust the width as needed */
            height: 500px;
        }
    </style>
</head>
<body style="background-color: #ffffff;">
<div class="overlay" id="overlay">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto text-center">
                <img class='loader' src="{% static 'loading.gif' %}" alt="Loading...">
                <h1>Loading...</h1>
            </div>
        </div>
    </div>
</div>
<div class="sidebar">
    {% if request.user.is_authenticated %}
        <a href="{% url 'profile_page' username=request.user.username %}">
            <img src="{% static 'leeri_logo.png' %}" alt="leari on a plane" style="margin-bottom: -45px">
        </a>
    {% else %}
        <img src="{% static 'leeri_logo.png' %}" alt="leari on a plane" style="margin-bottom: -45px">
    {% endif %}
    <p>Airplane Learning</p>
    {% if request.user.is_authenticated %}
        <hr>
        <p>Logged in as: {{ request.user.username }}</p>
        <hr>
        {% if user.profile %}
            {% url 'profile_page' username=user.username as profile %}
            {% url 'modules_list' language_id=user.profile.chosen_language.id as modules %}
            {% url 'main_forum_page' as forums %}
            {% url 'resources' as resources_page %}
            {% url 'feedback' as feedback %}
            {% url 'profile_settings' as settings %}
            {% url 'about' as about %}
            <span class="{% if request.path == profile %} active-link {% endif %}"><a href="{% url 'profile_page' username=request.user.username %}">Profile</a></span>
            <span class="{% if request.path == modules %}active-link{% endif %}"><a href="{% url 'modules_list' language_id=user.profile.chosen_language.id %}">Modules</a></span>
            <span class="{% if request.path == forums %}active-link{% endif %}"><a href="/forums/">Discussion Forums</a></span>
            <span class="{% if request.path == resources_page %}active-link{% endif %}"><a href="/resources/">Resource Library</a></span>
            <span class="{% if request.path == feedback %}active-link{% endif %}"><a href="/feedback/">Feedback Form</a></span>
            <span class="{% if request.path == settings %}active-link{% endif %}"><a href="{% url 'profile_settings' %}">Settings</a></span>
            <a class="{% if request.path == '/schema-swagger-ui/' %}active-link{% endif %}" href="{% url 'schema-swagger-ui' %}">Swagger</a>
        {% endif %}
        <span class="{% if request.path == '/logout/' %}active-link{% endif %}"> <a href="{% url 'logout' %}">Log out</a></span>
    {% endif %}
    <span class="{% if request.path == about %}active-link{% endif %}"> <a href="{% url 'about' %}">About</a></span>
</div>
<div class="content">
    {% block content %}{% endblock %}
</div>
{% bootstrap_javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $("a[href*='" + location.pathname + "']").addClass("active-link");
    });
    $(window).on('load', function() {
        setTimeout(function() {
            $("#overlay").fadeOut();
        }, 2000);
    });
</script>
</body>
</html>

templates/dictionary.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sniglet:wght@400;800&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>Dictionary</title>
</head>
<body>
<article class="sidebar">
    <a class="sniglet" href="{% url "profile_page" username=request.user.username %}"><img src="{% static "/leeri_logo.png" %}" style="height: 210px; width: 210px; margin-left: -10px; margin-bottom: -50px" alt="leari on a plane"></a>
    <p class="sniglet" style="color: white; font-size: 25px">Airplane Learning</p>
    <hr style="color: white; width: 100%">
    <a class="sniglet">Logged in as: {{ request.user.username }}</a>
    <hr style="color: white; width: 100%">
    <a class="sniglet" href="{% url "profile_page" username=request.user.username %}">Profile</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url "modules_list" language_id=user.profile.chosen_language.id %}">Modules</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="/forums">Discussion Forums</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="/resources">Resource Library</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="/feedback">Feedback Form</a>
    <br>
    <br>
    <a href="{% url 'profile_settings' %}" class="sniglet" style="font-size: 15px; ">Settings</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url 'schema-swagger-ui' %}">Swagger</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url 'logout' %}">Log out</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url 'about' %}">About</a>
    <footer class="sniglet" style="bottom: 45px; left: 75px">
        <p>© gearbeagel</p>
    </footer>
</article>
    <h1 class="sniglet" style="margin-left: 800px;">Dictionary</h1>
<span style="display: flex; flex-direction: row"> 
    <form action="{% url 'dictionary' %}" method="post" style="margin-left: 400px; margin-top: 50px; border: #d39c3f 3px solid; border-radius: 25px; width: fit-content; height: fit-content; padding: 10px">
        {% csrf_token %}
        <label class="sniglet" style="font-size: 30px; margin-left: 165px;" for="word">Enter a Word:</label>
        <br>
        <input type="text" name="word" id="word" class="sniglet" style="width: 500px;  height: 40px; margin-bottom: 10px; margin-top: 10px">
        <br>
        <button style="margin-left: 50px" type="submit">Search</button>
    </form>
        <span style="display: flex; flex-direction: column; border-left: #d39c3f 3px solid; margin-left: 60px">
        {% if meanings %}
         <h2 class="sniglet" style="margin-top: 60px; margin-left: 50px">"{{ word }}" means:</h2>
    <ul style="list-style-type: none; margin-left: 50px; margin-top: 20px; border: #d39c3f 3px solid; border-radius: 25px; width: 600px; padding: 10px">
        {% for meaning in meanings %}
        <li>{{ meaning }}
        <hr style="border: none; border-top: 3px solid #d39c3f; width: 100%; margin-top: 20px;"></li>
        {% endfor %}
    </ul>
    {% else %}
        <p style="margin-left: 200px; margin-top: 60px">No meaning for "{{ word }}" found. :(</p>
    {% endif %}
        </span>
</span>
</body>
</html>

templates/learning_path_choice.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sniglet:wght@400;800&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>Make a choice</title>
</head>
<body>
    <h2 class="sniglet" style="justify-content: center; display: flex; flex-wrap: wrap;">Before we start, it would be great if you could answer a couple of questions.</h2>
    <div class="container" style="margin: 0 0 0 0; border: none; position: absolute">
    <form method="post" action="{% url 'setup' %}">
        {% csrf_token %}
         <div class="column" style="margin: -200px 0 0 -600px">
            <h3 class="sniglet">Which language would you like to focus on?</h3>
            {% for language in form.chosen_language.field.queryset %}
                <label class="sniglet">
                    <input type="radio" name="chosen_language" value="{{ language.id }}">{{ language.name }}
                </label>
                {% if language.joke %}
                    <p>{{ language.joke }}</p>
                {% endif %}
                <br>
            {% endfor %}
        </div>
        <div class="column" style="margin: -200px 0 0 100px">
            <h3 class="sniglet">Choose a learning path for that language:</h3>
            {% for lp in form.learner_type.field.queryset %}
                <label class="sniglet">
                    <input type="radio" name="learner_type" value="{{ lp.id }}">{{ lp.title }}
                </label>
                <p>{{ lp.description }}</p>
                <br>
            {% endfor %}
        </div>
    <button type="submit" class="submit-button" style="position: relative; top: 275px; left: -250px">Submit</button>
    </form>
    </div>
</body>
</html>

templates/lesson_quiz.html
{% load quiz_extras %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sniglet:wght@400;800&display=swap" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>{{ quiz.title }}</title>
</head>
<body>
<article class="sidebar">
    <a class="sniglet" href="{% url "profile_page" username=request.user.username %}"><img src="{% static "/leeri_logo.png" %}" style="height: 210px; width: 210px; margin-left: -10px; margin-bottom: -50px" alt="leari on a plane"></a>
    <p class="sniglet" style="color: white; font-size: 25px">Airplane Learning</p>
    <hr style="color: white; width: 100%">
    <a class="sniglet">Logged in as: {{ request.user.username }}</a>
    <hr style="color: white; width: 100%">
    <a class="sniglet" href="{% url "profile_page" username=request.user.username %}">Profile</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url "modules_list" language_id=user.profile.chosen_language.id %}">Modules</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="/forums">Discussion Forums</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="/resources">Resource Library</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="/feedback">Feedback Form</a>
    <br>
    <br>
    <a href="{% url 'profile_settings' %}" class="sniglet" style="font-size: 15px; ">Settings</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url 'schema-swagger-ui' %}">Swagger</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url 'logout' %}">Log out</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url 'about' %}">About</a>
    <footer class="sniglet" style="bottom: 45px; left: 75px">
        <p>© gearbeagel</p>
    </footer>
</article>

    <h1 class="sniglet" style="margin-left: 700px">{{ quiz.title }}</h1>
    <p style="margin-left: 350px">{{ quiz.description }}</p>
    <p style="margin-left: 350px; 
            {% if quiz.difficulty_level == 'Easy' %} 
                background-color: #578661; /* Easy */
            {% elif quiz.difficulty_level == 'Medium' or 'medium' %}
                background-color: #d39c3f; /* Medium */
            {% elif quiz.difficulty_level == 'Hard' %}
                background-color: #CC6666; /* Hard */
            {% endif %}; padding: 10px 40px 10px 40px; border-radius: 20px; color: white; width: 40px">{{ quiz.difficulty_level }}</p>
    <br>
{% if quiz_status.status == "Not Started" %}
    <form method="post" action="{% url 'quiz_result' language.id quiz.id %}">
        {% csrf_token %}
        {% for question in questions %}
            <h3 class="sniglet" style="margin-left: 400px; padding: 10px; border: #d39c3f 3px solid; border-radius: 25px; width: fit-content">{{ question.text }}</h3>
            {% if question.question_type == 'Single Choice' %}
                {% for answer in answers_dict|get_value:question %}
                    <label class="sniglet" style="margin-left: 450px">
                        <input type="radio" name="question_{{ question.id }}" value="{{ answer.id }}">
                        {{ answer.text }}
                    </label><br>
                {% endfor %}
            {% elif question.question_type == 'Multiple Choice' %}
            {% for answer in question.answer_set.all %}
                <label class="sniglet" style="margin-left: 450px">
                    <input type="checkbox" name="question_{{ question.id }}" value="{{ answer.id }}">
                    {{ answer.text }}
                </label><br>
            {% endfor %}
            {% elif question.question_type == 'Open Text' %}
                <label>
                    <textarea name="question_{{ question.id }}" rows="4" cols="50" style="margin-left: 450px; font-family: Sniglet, sans-serif"></textarea>
                </label><br>
            {% endif %}
        {% endfor %}
        <br>
        <button type="submit" style="margin-left: 815px">Submit</button>
    </form>
{% elif quiz_status.status == "Completed" %}
    <p style="margin-left: 825px">You have already passed the quiz. You can view the results <a style='color: #637d91' href="{% url "quiz_result" language_id=language.id quiz_id=quiz.id %}">here.</a> </p>
{% endif %}
    </form>
</body>
</html>

templates/modules_main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sniglet:wght@400;800&display=swap" rel="stylesheet">
    <title>All Languages</title>
</head>
<body>
<article class="sidebar">
    
    <a href="/profile"><img src="{% static "/leeri_logo.png" %}" style="height: 30%; width: 115%; margin-left: -10px; margin-bottom: -50px" alt="leari on a plane"></a>
    <p class="sniglet" style="color: white; font-size: 30px">Airplane Learning</p>
    <a class="sniglet" style="font-size: 15px" href="/langs">Go to all languages</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="/forums">Go to discussion forums</a>
    <br>
    <br>
    <a href="{% url 'profile_settings' %}" class="sniglet" style="font-size: 15px; ">Go to settings</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url 'about' %}">About</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url 'logout' %}">Log out</a>
    <br>
    <br>
    <a class="sniglet" style="font-size: 15px" href="{% url 'schema-swagger-ui' %}">Swagger</a>
    <footer class="sniglet" style="bottom: 45px; left: 75px">
    <p>© gearbeagel</p>
    </footer>
    
</article>
    
<h1 class="sniglet-extrabold" style="text-align: center">Choose a language to learn</h1>
<div class="column">
    {% for language in languages %}
            <button class="modules sniglet"><a href="{% url 'modules_list' language.id %}">{{ language.name }}</a></button>
            <p>{{ language.joke }}</p>
        <br>
    {% endfor %}
</div>
</body>
</html>

templates/register.html
{% load socialaccount %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Sniglet:wght@400;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static "favicon.ico" %}">
    <title>Register</title>
</head>
<body>
<section class="row">
    <img src="{% static 'leeri_stare.png' %}" class='image' alt="Leeri staring into your soul">
    <div class="registration">
        <h2 class="sniglet">Register/Login with Google</h2>
        <a href="{% provider_login_url 'google' %}?next=/setup"><button class="reg-button">
        <img src="https://www.svgrepo.com/show/475656/google-color.svg" loading="lazy" alt="google logo" style="height: 25%;
    width: 25%;">Get Started</button></a>
</div>
</section>
<footer class="sniglet" style="color: #578661">
    <p>© gearbeagel</p>
</footer>
</body>
</html>